//Norman Pang 2019

//static variable for the number of beds on ITU
var numberofbeds = 22;

//static array for the intention rounding criteria
var columns = [
  "Bed number",
  "Line sites:accurate, dressing, time and date",
  "Biopatch",
  "Line removal appropriate site",
  "Height on CIS matches vent height",
  "Infection stated and appropriate PPE",
  "Pro cath done",
  "Vent tubing correct",
  "OOHCA bundle in place",
  "VAP bundle in place",
  "NOK recorded in last 24hrs",
];

//main function to generate the table. takes the arguments:
//'table' is the html table object. 'headers' are the intention rounding criteria
function generateTable(table, headers) {

  //creating table headers
  var thead = table.createTHead();
  var row = thead.insertRow();
  for (var h of headers){
    var th = document.createElement("th");
    var text = document.createTextNode(h);
    th.appendChild(text);
    row.appendChild(th);
  }
  //creating table body. initial for loop creates each row
  //setting r as 1 to reflect real bed number rather than index number to use later
  //first for loop to create each row one by one (starting at r=1)
  for (var r=1; r <= numberofbeds; r++) {
    var row = table.insertRow();
    var bedNumber = row.insertCell();
    //putting in the bed number in the first column
    bedNumber.appendChild(document.createTextNode(r));
    //the next for loop to create each of the relevant cells with radio buttons in each row
    //stops at < number of columns-1 to account for the initial bed number column
    for (var b=0; b<(columns.length-1); b++){
      var cell = row.insertCell();
      //creates the radio buttons with a unique id per cell. the unique cell ID is
      //generated by using the row number + intention rounding criterion
      var yesRadio = makeRadioButton(r+columns[b], "yes", "Yes");
      cell.appendChild(yesRadio);
      var noRadio = makeRadioButton(r+columns[b], "no", "No");
      cell.appendChild(noRadio);
      var naRadio = makeRadioButton(r+columns[b], "na", "NA");
      cell.appendChild(naRadio);
    }
  }
}

//custom function to create dynamically generate radio buttons
//id is the unique ID per cell (otherwise the radio buttons wont work independently per cell)
//value is what is stored and returned from the html document. name is the visible text
function makeRadioButton(id, value, text) {

    var label = document.createElement("label");
    var radio = document.createElement("input");
    radio.type = "radio";
    radio.name = id;
    radio.value = value;

    label.appendChild(radio);
    label.appendChild(document.createTextNode(text));
    return label;
  }

//getting the table (id name 'dataTable') and putting it into a variable
var dataTable = document.getElementById("dataTable");
generateTable(dataTable, columns);
